---
groupsUrl: "file:///etc/calamares/modules/netinstall-cabbage.yaml"
required: false
label:
    sidebar: "CabbageOS Selection"
    sidebar[he]: "בחירת תוכנה"
    sidebar[de]: "Software-Auswahl"
    sidebar[fi]: "Ohjelmistovalinta"
    sidebar[fr]: "Sélection de logiciels"
    sidebar[it]: "Selezione del software"
    sidebar[sp]: "Selección de software"
    sidebar[ru]: "Выבור программного обеспечения"
    sidebar[zh_CN]: "软件选择"
    sidebar[ja]: "ソフトウェア選択"
